title: AI Course
description: Artificial Intelligence Course at University of Tehran
theme: just-the-docs

url: https://just-the-docs.github.io
favicon_ico: /assets/image/AI-logo.ico

aux_links:
  "Elearn":
    - "https://elearn4.ut.ac.ir/course/view.php?id=14671"

  "Dark Mode":
    - "javascript:const toggleDarkMode = document.querySelector('.js-toggle-dark-mode'); jtd.addEvent(toggleDarkMode, 'click', function(){ if (jtd.getTheme() === 'dark') { jtd.setTheme('light'); toggleDarkMode.textContent = 'Dark Mode'; } else { jtd.setTheme('dark'); toggleDarkMode.textContent = 'Light Mode'; } });"